### ISSUE TITLE
Replace psycopg2-binary by psycopg2

### ISSUE THREAD

**Issue by pspachtholz** [comsysto/eCharm#43]
Hi guys,

I just ran the eCharm pipeline that @LarsHaferkampEON implemented on my M1 mac and ran into an issue.
The error i received was "SCRAM authentication requires libpq version 10 or above". 

It looks like the libpq version that is used by psycopg2 on m1 macs is too below 9. The easiest workaround to this
is replacing the psycopg2-binary in requirements by the psycopg2 package. 

See [this link](https://stackoverflow.com/a/70661763) for a similar issue.

**Comment by stefanpernpaintner** [comment]
This issue was fixed with https://github.com/comsysto/eCharm/pull/48
